<a href="https://colab.research.google.com/github/VictorRamires/datascience/blob/main/k_means_random.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from sklearn.datasets import make_blobs
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans

In [ ]:
#gera numeros aleatorios, 200 numeros aleatorios com 5 clusters
x_random, y_random = make_blobs(n_samples = 200, centers = 5)
x_random

array([[ 3.77888478e-01, -9.46876697e-03],
       [-8.16399932e+00,  5.25432683e+00],
       [-5.35306061e+00,  1.93398936e+00],
       [-5.33476526e+00, -2.14578395e+00],
       [-1.62988587e+00,  1.82936655e+00],
       [-5.48184455e+00,  1.74434744e+00],
       [ 1.22427127e-01,  9.60739844e+00],
       [-3.27595448e+00,  6.23538184e+00],
       [-8.80755607e-01,  4.03203204e-01],
       [-3.73373375e+00, -7.96817977e-01],
       [-3.78944538e+00, -1.81599240e+00],
       [-9.01864769e-01,  1.00618975e+01],
       [-8.13672645e+00,  3.91033855e+00],
       [-5.94986220e+00,  1.28794856e+00],
       [-3.91848954e+00,  2.70111183e-01],
       [-1.77531097e+00,  5.02315079e+00],
       [ 6.28689768e-01,  1.00007262e+01],
       [-4.73465188e-01,  4.34762256e+00],
       [-4.80634396e+00,  1.48920437e+00],
       [-8.41398645e-01,  3.49279071e-01],
       [-7.05193281e-02,  2.14925386e-01],
       [-4.47350910e+00,  4.81111363e+00],
       [-1.04067184e+01,  3.17827572e+00],
       [-1.

In [ ]:
kmeans_blobs = KMeans(n_clusters = 5)
kmeans_blobs.fit(x_random)

KMeans(n_clusters=5)

In [ ]:
rotulos = kmeans_blobs.predict(x_random)
rotulos

array([2, 0, 4, 4, 2, 4, 3, 1, 2, 4, 4, 3, 0, 4, 4, 1, 3, 1, 4, 2, 2, 1,
       0, 3, 2, 4, 0, 0, 0, 1, 4, 3, 3, 3, 3, 4, 0, 0, 4, 2, 3, 0, 4, 1,
       0, 0, 0, 4, 1, 2, 2, 0, 1, 1, 3, 3, 0, 3, 4, 2, 4, 0, 3, 3, 0, 0,
       4, 4, 2, 3, 3, 4, 1, 4, 0, 1, 0, 1, 3, 1, 4, 4, 1, 2, 0, 2, 1, 2,
       2, 2, 4, 1, 1, 1, 0, 1, 1, 2, 1, 2, 0, 1, 3, 3, 2, 3, 2, 3, 2, 0,
       1, 1, 2, 3, 4, 3, 1, 4, 4, 3, 1, 0, 3, 1, 4, 3, 4, 1, 2, 4, 4, 0,
       3, 2, 3, 0, 3, 1, 0, 0, 0, 1, 2, 1, 4, 2, 4, 1, 0, 2, 4, 4, 3, 2,
       3, 2, 1, 1, 3, 2, 0, 0, 3, 1, 4, 3, 0, 3, 2, 0, 4, 0, 2, 2, 0, 4,
       0, 2, 2, 1, 3, 1, 3, 4, 2, 0, 2, 3, 1, 0, 1, 4, 3, 4, 1, 4, 0, 3,
       4, 2], dtype=int32)

In [ ]:
centroides = kmeans_blobs.cluster_centers_
centroides

array([[-9.350806  ,  3.53872686],
       [-2.95085611,  4.88323485],
       [-1.49741952,  0.80696689],
       [ 0.69456896,  9.59342713],
       [-5.07792098, -0.31630077]])

In [ ]:
grafico_pontos = px.scatter(x = x_random[:,0], y = x_random[:,1], color = rotulos)
#grafico_pontos.show()
grafico_centroides = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [3,3,3,3,3])
#grafico_centroides.show()
grafico_final = go.Figure(data = grafico_pontos.data + grafico_centroides.data)
grafico_final.show()