<a href="https://colab.research.google.com/github/VictorRamires/datascience/blob/main/k_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

In [3]:
from sklearn.cluster import KMeans


In [4]:
#criamos duas variaveis, X com as ideiades e Y com os salarios
#Exemplo
x=[20,  27,  21,  37,  46, 53, 55,  47,  52,  32,  39,  41,  39,  48,  48]  
y=[1000,1200,2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]

grafico = px.scatter(x = x, y = y) #grafico de dispersão
grafico.show()

Unindo as duas variaveis em um formato de matriz

In [5]:
dicionario = dict(zip(x, y))
base_salario = np.array(list(dicionario.items()))
base_salario

array([[  20, 1000],
       [  27, 1200],
       [  21, 2900],
       [  37, 1850],
       [  46,  900],
       [  53,  950],
       [  55, 2000],
       [  47, 2100],
       [  52, 3000],
       [  32, 5900],
       [  39, 7000],
       [  41, 5100],
       [  48, 6500]])

Colocando os dados de salario e idade na mesma escala

In [6]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)
base_salario

array([[-1.73975199, -0.98177935],
       [-1.12611854, -0.8886178 ],
       [-1.65209007, -0.09674468],
       [-0.24949932, -0.58584279],
       [ 0.53945798, -1.02836012],
       [ 1.15309144, -1.00506973],
       [ 1.32841528, -0.51597163],
       [ 0.6271199 , -0.46939086],
       [ 1.06542951, -0.05016391],
       [-0.68780893,  1.30067848],
       [-0.07417547,  1.81306697],
       [ 0.10114837,  0.9280323 ],
       [ 0.71478183,  1.58016311]])

Inicializando o algoritmo com 3 clusters 

In [8]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [10]:
centroides = kmeans_salario.cluster_centers_
centroides
#aqui temos 3 registro, um centroide para cada um dos clusters 
#cada centroide é caracterizado pela media dos registros que compoes aquele cluster (classe)



array([[-1.50598687, -0.65571394],
       [ 0.74400247, -0.60913317],
       [ 0.01348645,  1.40548522]])

Vizualizando os centroides utilizando o processo inverso

In [11]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)
#média dos itens que compoe aquele grupo

array([[  22.66666667, 1700.        ],
       [  48.33333333, 1800.        ],
       [  40.        , 6125.        ]])