<a href="https://colab.research.google.com/github/VictorRamires/datascience/blob/main/k_means.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import plotly.express as px
import plotly.graph_objects as go
import numpy as np
from sklearn.preprocessing import StandardScaler

In [ ]:
from sklearn.cluster import KMeans


In [ ]:
#criamos duas variaveis, X com as ideiades e Y com os salarios
#Exemplo
x=[20,  27,  21,  37,  46, 53, 55,  47,  52,  32,  39,  41,  39,  48,  48]  
y=[1000,1200,2900,1850,900,950,2000,2100,3000,5900,4100,5100,7000,5000,6500]

grafico = px.scatter(x = x, y = y) #grafico de dispersão
grafico.show()

Unindo as duas variaveis em um formato de matriz

In [ ]:
#dicionario = dict(zip(x, y))
#base_salario = np.array(list(dicionario.items()))
#base_salario

#como existem valores iguais no campo chave, ficou faltando valores
#portanto a inserção será feita manualmente

base_salario = np.array([[20,1000],[27,1200],[21,2900],[37,1850],[46,900],
                        [53,950],[55,2000],[47,2100],[52,3000],[32,5900],
                        [39,4100],[41,5100],[39,7000],[48,5000],[48,6500]])

Colocando os dados de salario e idade na mesma escala

In [ ]:
scaler_salario = StandardScaler()
base_salario = scaler_salario.fit_transform(base_salario)
base_salario

array([[-1.87963884, -1.11413572],
       [-1.23255006, -1.01725435],
       [-1.78719758, -0.19376273],
       [-0.30813751, -0.70238991],
       [ 0.52383377, -1.1625764 ],
       [ 1.17092255, -1.13835606],
       [ 1.35580506, -0.62972888],
       [ 0.61627503, -0.5812882 ],
       [ 1.0784813 , -0.14532205],
       [-0.77034379,  1.25945777],
       [-0.12325501,  0.38752547],
       [ 0.0616275 ,  0.8719323 ],
       [-0.12325501,  1.79230528],
       [ 0.70871628,  0.82349162],
       [ 0.70871628,  1.55010187]])

Inicializando o algoritmo com 3 clusters 

In [ ]:
kmeans_salario = KMeans(n_clusters=3)
kmeans_salario.fit(base_salario)

KMeans(n_clusters=3)

In [ ]:
centroides = kmeans_salario.cluster_centers_
centroides
#aqui temos 3 registro, um centroide para cada um dos clusters 
#cada centroide é caracterizado pela media dos registros que compoes aquele cluster (classe)



array([[ 0.07703438,  1.11413572],
       [ 0.73953003, -0.72661025],
       [-1.63312883, -0.77505093]])

Vizualizando os centroides utilizando o processo inverso

In [ ]:
scaler_salario.inverse_transform(kmeans_salario.cluster_centers_)
#média dos itens que compoe aquele grupo

array([[  41.16666667, 5600.        ],
       [  48.33333333, 1800.        ],
       [  22.66666667, 1700.        ]])

In [ ]:
#quantidade de rótulos que estão em cada um dos clusters [0,1,2]
rotulos = kmeans_salario.labels_
rotulos

array([2, 2, 2, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0], dtype=int32)

In [ ]:
grupos_grafico = px.scatter(x = base_salario[:,0], y = base_salario[:,1], color = rotulos)
grupos_grafico.show()
#o argumento rotulos define as cores

In [ ]:
#mostrando a posição dos centroides
centroides_grafico = px.scatter(x = centroides[:,0], y = centroides[:,1], size = [10,10,10])
centroides_grafico.show()

Combinando os dois graficos para ver os 
dados e os centroides

In [ ]:
todos_dados_grafico = go.Figure(data = centroides_grafico.data + grupos_grafico.data)
todos_dados_grafico.show()